# -*- coding: utf-8 -*-
"""Lung.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_N-O0bRqpK-jmQDMBZummWQrJf4IjUlf
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Loading data
lung_cancer_data = pd.read_csv('/content/Lung Cancer (1).csv')

lung_cancer_data.head()

lung_cancer_data.isnull().sum()

print(lung_cancer_data['family_history'].mode())

lung_cancer_data['family_history'].fillna(lung_cancer_data['family_history'].mode()[0], inplace= True)

print(lung_cancer_data['cancer_stage'].mode())

lung_cancer_data['cancer_stage'].fillna(lung_cancer_data['cancer_stage'].mode()[0], inplace= True)

print(lung_cancer_data['smoking_status'].mode())

lung_cancer_data['smoking_status'].fillna(lung_cancer_data['smoking_status'].mode()[0], inplace= True)

print(lung_cancer_data['cholesterol_level'].mode())

lung_cancer_data['cholesterol_level'].fillna(lung_cancer_data['cholesterol_level'].mean(), inplace= True)

print(lung_cancer_data['hypertension'].mode())

lung_cancer_data['hypertension'].fillna(lung_cancer_data['hypertension'].mean(), inplace= True)

print(lung_cancer_data['asthma'].mode())

lung_cancer_data['asthma'].fillna(lung_cancer_data['asthma'].mean(), inplace= True)

print(lung_cancer_data['cirrhosis'].mode())

lung_cancer_data['cirrhosis'].fillna(lung_cancer_data['cirrhosis'].mean(), inplace= True)

print(lung_cancer_data['other_cancer'].mode())

lung_cancer_data['other_cancer'].fillna(lung_cancer_data['other_cancer'].mean(), inplace= True)

print(lung_cancer_data['treatment_type'].mode())

lung_cancer_data['treatment_type'].fillna(lung_cancer_data['treatment_type'].mode(), inplace= True)

print(lung_cancer_data['survived'].mode())

lung_cancer_data['survived'].fillna(lung_cancer_data['survived'].mode(), inplace= True)

lung_cancer_data = lung_cancer_data.drop(columns=['id','country','end_treatment_date', 'diagnosis_date'])

print(lung_cancer_data['cancer_stage'].value_counts())

print(lung_cancer_data['smoking_status'].value_counts())

print(lung_cancer_data['treatment_type'].value_counts())

lung_cancer_data.replace({
    'gender': {'Male': 0, 'Female': 1},
    'cancer_stage': {
        'Stage I': 1,
        'Stage II': 2,
        'Stage III': 3,
        'Stage IV': 4
    },
    'family_history': {'Yes': 1, 'No': 0},
    'smoking_status': {
        'Never Smoked': 0,
        'Former Smoker': 1,
        'Passive Smoker': 2,
        'Current Smoker': 3
    },
    'treatment_type': {
        'Surgery': 0,
        'Radiation': 1,
        'Chemotherapy': 2,
        'Combined': 3
    }
}, inplace=True)

print(lung_cancer_data.head())

"""
Sperating features and Target"""

lung_cancer_data['survived'].fillna(lung_cancer_data['survived'].mode(), inplace= True)

X = lung_cancer_data.drop(columns=['survived'], axis=1)
Y = lung_cancer_data['survived']

Y.isna().sum()

Y.fillna(Y.mode()[0],inplace = True)

X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y, test_size=0.2, stratify=Y, random_state=42
)

from sklearn.utils import class_weight
class_weights = class_weight.compute_class_weight('balanced', classes=np.unique(Y_train), y=Y_train)

from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier

from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

# define your model
model = LogisticRegression()

# now this works
cv_scores = cross_val_score(model, X, Y, cv=5)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print(X.shape, X_train.shape, X_test.shape)

"""Model training using LogisticRegeration technic"""

X.isna().sum()

X.fillna(X['treatment_type'].mode()[0],inplace = True)

X.isna().sum()

X.isna().sum()

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

X.isna().sum()

Y.isna().sum()

model = LogisticRegression(max_iter=1000)  # Increase iterations
model.fit(X_train, Y_train)

model.fit(X_train, Y_train)

X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(Y_train, X_train_prediction)

print(training_data_accuracy)

X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(Y_test, X_test_prediction)

from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(Y_test, X_test_prediction))
print(confusion_matrix(Y_test, X_test_prediction))

import joblib

joblib.dump(model, "model.joblib")